name: epi2melabs-wf-human-sv
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.3.5
    - pysam
    - fastcat
    - lra
    - samtools
    - cutesv

